name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta todos los días a la medianoche UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Dulc1
          outputs: |
            ./resources/img/github-contribution-grid-snake.svg
